pipeline:
  name: aks-gitops-deployment
  identifier: aksgitopsdeployment
  projectIdentifier: akswebapi
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: aks-gitops-deployment
        identifier: aksgitopsdeployment
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          execution:
            steps:
              - step:
                  type: GitOpsUpdateReleaseRepo
                  name: Update Release Repo
                  identifier: updateReleaseRepo
                  timeout: 10m
                  spec:
                    variables: []
                    delegateSelectors:
                      - helm-delegate
                  failureStrategies: []
              - step:
                  type: MergePR
                  name: Merge PR
                  identifier: mergePR
                  spec:
                    deleteSourceBranch: true
                    variables: []
                    delegateSelectors:
                      - helm-delegate
                  timeout: 10m
                  failureStrategies: []
              - step:
                  type: GitOpsFetchLinkedApps
                  name: Fetch Linked Apps
                  identifier: fetchLinkedApps
                  timeout: 10m
                  spec:
                    delegateSelectors:
                      - helm-delegate
                  failureStrategies: []
            rollbackSteps: []
          service:
            serviceRef: aksgitopsservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev_1681976941706
            deployToAll: true
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
